// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getEnv } from "@/lib/runtime-env.server";

function createSupabaseAdminClient() {
  const SUPABASE_URL = getEnv("SUPABASE_URL");
  const SUPABASE_SERVICE_ROLE_KEY = getEnv("SUPABASE_SERVICE_ROLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    // throw 대신 경고만 남기고 더미 URL/키로 클라이언트 생성
    // 실제 DB 요청 시 error 객체로 반환되므로 각 호출 지점에서 처리
    console.warn(
      `[Supabase] Missing env: ${missing.join(", ")} — DB operations will fail gracefully`,
    );
    return createClient<Database>(
      SUPABASE_URL ?? "https://placeholder.supabase.co",
      SUPABASE_SERVICE_ROLE_KEY ?? "placeholder-key",
      { auth: { storage: undefined, persistSession: false, autoRefreshToken: false } },
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// Always create fresh — Cloudflare Workers env bindings are set per-request via setCfEnv()
// and the URL/key never change, so this is safe and avoids stale-env caching issues.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    return Reflect.get(createSupabaseAdminClient(), prop, receiver);
  },
});
